export const ADD_TODO = "ADD_TODO";
export const REM_TODO = "REM_TODO";

export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const GET_TODO_LOADING = "GET_TODO_LOADING";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_ERROR = "GET_TODO_ERROR";

export const DEL_TODO_LOADING = "DEL_TODO_LOADING";
export const DEL_TODO_SUCCESS = "DEL_TODO_SUCCESS";
export const DEL_TODO_ERROR = "DEL_TODO_ERROR";

export const UPD_TODO_LOADING = "UPD_TODO_LOADING";
export const UPD_TODO_SUCCESS = "UPD_TODO_SUCCESS";
export const UPD_TODO_ERROR = "UPD_TODO_ERROR";
